[versions]
agp = "8.5.0"
kotlin = "2.0.20"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
googleKsp = "2.0.20-1.0.25"
hilt = "2.52"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
devtoolsKsp = { id = "com.google.devtools.ksp", version.ref = "googleKsp" }

hilt_android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

